export const formStyles = {
    form:                   "mt-8 rounded-2xl border border-cyan-400/30 bg-white/5 p-4",
    formDivGridCol3:        "mt-6 grid gap-5 md:grid-cols-3",
    formDivCyan:            "mt-4 rounded-xl border border-cyan-400/30 bg-cyan-400/10 p-4",
    formInfoCellCaption:    "text-slate-300",
    formInfoCell:           "block text-sm text-slate-400",
    inputWFull:             "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-full", //with w-full 
    inputNumber:            "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-26",
    input:                  "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300",
    selectWFull:            "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-full",
    selectForm:             "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300",
    label:                  "block text-sm font-medium text-slate-200",
    info:                   "rounded-2xl border-3 border-cyan-400/30 bg-slate-950 p-5",
    textarea:               "rounded-lg border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300",
    //primaryButtonOutside:   "rounded-xl border border-cyan-400/30 bg-cyan-400/10 text-base font-semibold text-cyan-100 hover:bg-cyan-400/20 px-7 py-5 mt-6 ",
    primaryButtonOutside:   "inline-flex h-10 w-fit items-center justify-center rounded-xl border-4 border-cyan-400/30 bg-cyan-400/10 px-4 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20",
    primaryButtonInside:    "rounded-xl border-3 border-cyan-400/30 bg-cyan-400/10 text-base font-semibold text-cyan-100 hover:bg-cyan-400/20 px-5 py-3 ",
    primaryButtonDP:        "rounded-xl border-4 border-cyan-400/30 bg-cyan-400/10 px-4 text-sm font-semibold leading-none text-cyan-100 hover:bg-cyan-400/20 mt-1 h-12 w-fit self-start ",//phone: full width, desktop: small width
    smallButton:            "rounded-lg border border-cyan-400/30 bg-cyan-400/10 px-3 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20",
    link:                   "text-sm text-cyan-300 hover:text-cyan-200",
    linkHref:               "mt-4 inline-block rounded-xl border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20",
    span:                   "mb-2 block text-sm font-medium text-slate-300",
    formInputInfoCaption:    "text-md text-slate-400",
    formInputInfoValue:     "mt-2 font-medium",
    sectionCardCyan:        "rounded-2xl border-3 border-cyan-400/30 bg-white/5 p-6 hover:bg-white/10",
    formCaptionSmall:       "text-sm font-semibold tracking-[0.3em] text-cyan-300",
    formP:                  "mt-2 text-sm text-slate-300",
    formLabel:              "text-sm font-semibold text-cyan-200",     
    formH3SemiBold:         "text-xl font-semibold text-white",            
    formSemiBold:           "font-semibold text-white",   
    formSuccessMsg:         "mt-8 rounded-2xl border border-green-400/30 bg-green-400/10 p-4 text-green-200",          
};

export const pageStyles = {
    main:                     "min-h-screen bg-slate-950 px-6 py-16 text-white",
    container:                "mx-auto max-w-7xl",
    containerMedium :         "mx-auto max-w-6xl",
    containersmall:           "mx-auto max-w-4xl",
    sectionCard:              "rounded-2xl border border-white/10 bg-white/5 p-6",
    sectionCardCyan:          "rounded-2xl border-3 border-cyan-400/30 bg-white/5 p-6 hover:bg-white/10",
    pageLabelTracking03:      "text-sm font-semibold tracking-[0.3em] text-cyan-300",
    pageLabel:                "text-sm font-semibold text-cyan-200",
    pageLabelUpper:           "text-sm font-semibold tracking-[0.3em] text-cyan-300 uppercase",
    
    pageTitle:                "mt-3 text-3xl font-bold text-white",
    
    pageDescription:          "mt-4 max-w-2xl text-slate-300",
    errorMessage:             "mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-200",
};

export const tableStyles = {
    wrapper:                  "mt-10 overflow-x-auto rounded-2xl border border-white/10 bg-white/5",
    table900:                 "w-full min-w-[900px] text-left text-sm",
    table1000:                "w-full min-w-[1000px] text-left text-sm",
    tableDiv:                 "mt-6 overflow-x-auto rounded-2xl border border-cyan-400/30 bg-white/5",
    tableWide:                "w-full min-w-[1200px] text-left text-sm",
    header:                   "border-b border-white/10 bg-white/10 text-slate-300",
    headerTable:              "mt-12 text-2xl font-bold",
    headerTableSmall:         "mt-8 text-md font-bold",
    tableHeaderCyan:          "border-b border-cyan-400/30 bg-cyan-400/10 text-slate-300",
    rowWhite:                 "border-b border-white/10",
    rowCyan:                  "border-b border-cyan-400/30",
    cell:                     "p-4 text-slate-300",
    cellEmpty:                "p-4 text-slate-300",
    cellInfo:                 "text-md text-slate-400",     
    cellStatusInfo:           "px-3 py-1 text-sm font-medium text-cyan-200",
    cellCaptionGroup:         "font-medium text-white",
    cellCaption:              "p-4",
    selectTable:              "rounded-lg border border-cyan-400/30 bg-slate-950 px-3 py-2 text-white outline-none focus:border-cyan-300",  
    statusYellowClasses:      "bg-yellow-600/25 text-yellow-50 ring-1 ring-yellow-500/40",
    statusGreenClasses:       "bg-green-600/25 text-green-50 ring-1 ring-green-500/40",
    statusRedClasses:         "bg-red-600/25 text-red-50 ring-1 ring-red-500/40",
    errorCell:                "mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200",
};