export const formStyles = {
    form:                   "mt-8 rounded-2xl border border-cyan-400/30 bg-white/5 p-4",
    formDivGridCol3:        "mt-6 grid gap-5 md:grid-cols-3",
    formDivGridCol2:        "mt-6 grid gap-4 text-sm text-slate-300 md:grid-cols-2",
    formDivCyan:            "mt-4 rounded-xl border border-cyan-400/30 bg-cyan-400/10 p-4",
    formDivFlex:            "flex items-start justify-between gap-4",
    formInfoCellCaption:    "text-slate-300",
    formBookingInfoCaption: "font-bold text-slate-400",
    formInfoCell:           "block text-sm text-slate-400",
    input:                  "rounded-lg border-3 border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300",
    inputWFullCyan:         "rounded-lg border-3 border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-full", //with w-full 
    inputWFullYellow:       "rounded-lg border-3 border-yellow-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-yellow-300 w-full", //with w-full 
    inputNumber:            "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-26",  
    selectWFull:            "rounded-lg border-3 border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-full",  //with w-full 
    selectForm:             "rounded-lg border border-cyan-400/30 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300",
    label:                  "block text-sm font-medium text-slate-200",
    info:                   "rounded-2xl border-3 border-cyan-400/30 bg-slate-950 p-5",
    textarea:               "rounded-lg border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-cyan-300 w-full",
    primaryButtonOutside:   "inline-flex h-10 w-fit items-center justify-center rounded-xl border-4 border-cyan-400/30 bg-cyan-400/10 px-4 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20",
    primaryButtonDP:        "rounded-xl border-4 border-cyan-400/30 bg-cyan-400/10 px-4 text-sm font-semibold leading-none text-cyan-100 hover:bg-cyan-400/20 mt-1 h-12 w-fit self-start ",//phone: full width, desktop: small width
    smallButton:            "shrink-0 rounded-lg border border-cyan-400/30 bg-cyan-400/10 px-3 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20 inline-flex items-center justify-center text-center",
    activateButton:         "rounded-full border border-cyan-400/30  px-4 py-2 text-sm font-semibold text-green-200 hover:bg-green-500/10",
    sctivateButtonPhone:     "rounded-2xl border border-cyan-400/30 bg-cyan-950/20 p-4 text-sm text-white opacity-50" ,
    deActiveDeleteButton:   "rounded-full border border-red-500/40 px-4 py-2 text-sm font-semibold text-red-200 hover:bg-red-500/10" ,
    deActivateButtonPhone:  "rounded-2xl border border-cyan-400/30 bg-cyan-950/20 p-4 text-sm text-white" ,
    link:                   "text-sm text-cyan-300 hover:text-cyan-200",
    linkHref:               "mt-4 inline-block rounded-xl border border-cyan-400/30 bg-cyan-400/10 px-4 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-400/20",
    span:                   "mb-2 block text-sm font-medium text-slate-300",
    formInputInfoCaption:    "text-md text-slate-400",
    formInputInfoValue:     "mt-2 font-medium",
    formLabel:              "text-sm font-semibold text-cyan-200",     
    formH3SemiBold:         "text-xl font-semibold text-white",   
    formH5MediumSemiBold:   "text-md font-semibold text-white", 
    formH5SmallSemiBold:    "text-sm font-semibold text-white",         
    sectionCardBorder4:     "rounded-2xl border-4 border-white/10 bg-white/5 p-6",   
    formP:                  "mt-2 text-sm text-slate-300",
    formPCyan:              "mt-2 text-sm text-cyan-300",
    formPYellow:            "mt-2 text-sm text-yellow-300",
    formCaptionUpTracking03:"font-semibold uppercase tracking-[0.3em] text-cyan-300",
    inputUserPage:          "w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none placeholder:text-slate-500 focus:border-yellow-400",
    inputDateUserPage:      "w-full rounded-xl border border-white/10 bg-slate-950 px-4 py-3 text-white outline-none focus:border-yellow-400",
    submitButtonUserPage:        "mt-8 rounded-full bg-yellow-400 px-8 py-4 font-semibold text-slate-950 transition hover:bg-yellow-300",
    submitSmallButtonUserPage:   "mt-8 rounded-full bg-yellow-400 px-5 py-2 text-sm font-semibold text-slate-950 transition hover:bg-yellow-300",
    formMt10: "mt-10 rounded-2xl border-2 border-white/10 bg-white/5 p-4 sm:p-6",
};

export const pageStyles = {
    main:                     "min-h-screen bg-slate-950 px-6 py-16 text-white",
    container:                "mx-auto max-w-7xl",
    containerMedium :         "mx-auto max-w-6xl",
    containersmall:           "mx-auto max-w-4xl",
    sectionCard:              "rounded-2xl border border-white/10 bg-white/5 p-6",
    sectionCardCyan:          "rounded-2xl border-3 border-cyan-400/30 bg-white/5 p-6 hover:bg-white/10",
    pageLabelTracking03:      "text-sm font-semibold tracking-[0.3em] text-cyan-300",
    pageLabel:                "text-sm font-semibold text-cyan-200",
    pageLabelUpper:           "text-sm font-semibold tracking-[0.3em] text-cyan-300 uppercase",
    pageTitle:                "mt-3 text-3xl font-bold text-white",
    pageDescription:          "mt-4 max-w-2xl text-slate-300",
    errorMsg:                 "mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-200",
    errorMsgPage:             "mt-6 rounded-xl border-3 border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200",
    successMsgPage:           "mt-6 rounded-xl border-3 border-cyan-500/30 bg-cyan-500/10 p-4 text-sm text-cyan-200",
    logButton:                "text-sm text-slate-300 hover:text-cyan-300",
    loginButtonHome:          "rounded-full border border-yellow-400 px-5 py-2 text-sm font-semibold text-yellow-300 hover:bg-yellow-400/10",
    divFlex:                  "flex items-start justify-between gap-4",

};
export const tableStyles = {
    wrapper:                  "mt-10 overflow-x-auto rounded-2xl border border-white/10 bg-white/5",
    table900:                 "w-full min-w-[900px] text-left text-sm",
    table1000:                "w-full min-w-[1000px] text-left text-sm",
    table1200:                "w-full min-w-[1200px] text-left text-sm",
    tableDiv:                 "mt-6 overflow-x-auto rounded-2xl border border-cyan-400/30 bg-white/5",
    tableWide:                "w-full min-w-[1200px] text-left text-sm",
    header:                   "border-b border-white/10 bg-white/10 text-slate-300",
    headerTable:              "mt-12 text-2xl font-bold",
    headerTableSmall:         "mt-8 text-md font-bold",
    tableHeaderCyan:          "border-b border-cyan-400/30 bg-cyan-400/10 text-slate-300",
    rowWhite:                 "border-b border-white/10",
    rowCyan:                  "border-b border-cyan-400/30",
    cell:                     "p-4 text-slate-300",
    cellEmpty:                "p-4 text-slate-300",
    cellInfo:                 "text-md text-slate-400",     
    cellStatusInfo:           "px-3 py-1 text-sm font-medium text-cyan-200",
    cellCaptionGroup:         "font-medium text-white",
    cellCaption:              "p-4",
    selectTable:              "rounded-lg border border-cyan-400/30 bg-slate-950 px-3 py-2 text-white outline-none focus:border-cyan-300",  
    statusYellowClasses:      "bg-yellow-600/25 text-yellow-50 ring-1 ring-yellow-500/40",
    statusGreenClasses:       "bg-green-600/25 text-green-50 ring-1 ring-green-500/40",
    statusRedClasses:         "bg-red-600/25 text-red-50 ring-1 ring-red-500/40",
    errorCell:                "mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200",
    DivCyanList:              "mt-4 rounded-xl border border-cyan-400/30 bg-cyan-400/10 p-4",
    okCheckSign:              "text-sm font-bold text-green-300",
};

export const mobileStyle ={
    inforCaption:                   "text-sm tracking-tight text-cyan-300",
    inforCaptionBold:               "text-sm tracking-tight text-cyan-300 font-bold wrap-break-word",
    infoValue:                      "mt-1 wrap-break-word text-white",
    infoValueBold:                  "mt-1 wrap-break-word text-white font-bold wrap-break-word ",
    selectOption:                   "rounded-lg border border-cyan-400/30 bg-slate-950 px-2 py-0 text-white text-sm outline-none focus:border-cyan-300 leading-tight h-7 w-42 ",
    article:                        "rounded-2xl border border-cyan-400/30 bg-cyan-950/20 p-4 text-sm text-white",
    line:                           "border-t border-cyan-400/60 pt-4"  ,
};