/*
  Root layout for the whole Voya Taxi application.

  This file controls the base HTML structure that wraps every page.
  We add LanguageProvider here so all pages and components can use
  the selected language, such as English or Dutch.

  Maintenance mode:
  When MAINTENANCE_MODE=true, the app shows MaintenancePage instead
  of the normal website.
*/

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "@/components/LanguageProvider";
import MaintenancePage from "@/components/MaintenancePage";
import "./globals.css";

const geistSans = Geist({  variable: "--font-geist-sans",  subsets: ["latin"],});
const geistMono = Geist_Mono({  variable: "--font-geist-mono",  subsets: ["latin"],});
export const metadata: Metadata = {  title: "Create Next App",  description: "Generated by create next app",};

// isMaintenanceMode reads the environment variable.
// If it is exactly "true", visitors see the maintenance page.
const isMaintenanceMode = process.env.MAINTENANCE_MODE === "true";

// RootLayout is the top-level layout component.
// Every page is rendered inside the children prop.
export default function RootLayout({ children,}: Readonly<{
  // children represents the page content that Next.js places inside this layout.
  children: React.ReactNode;
}>) {
  return (
    <html  lang="en"  className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}  >
      <body className="min-h-full flex flex-col"> {isMaintenanceMode ? ( <MaintenancePage /> ) : ( <LanguageProvider>{children}</LanguageProvider> )}
      </body>
    </html>
  );
}