/*
  Root layout for the whole Voya Taxi application.

  This file controls the base HTML structure that wraps every page.
  We add LanguageProvider here so all pages and components can later use
  the selected language, such as English or Dutch.
*/

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LanguageProvider } from "@/components/LanguageProvider";
import "./globals.css";

const geistSans = Geist({variable: "--font-geist-sans",subsets: ["latin"],});
const geistMono = Geist_Mono({variable: "--font-geist-mono", subsets: ["latin"],});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is the top-level layout for the whole application.
// We add LanguageProvider here so all pages can later read the selected language.
export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return ( <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} >
      <body className="min-h-full flex flex-col">
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
